### ISSUE TITLE
semantics of AddChild() after Close()

### ISSUE THREAD

**Issue by jbenet** [jbenet/goprocess#1]
Ran into an interesting case. suppose:

``` go
fire := make(chan struct{})
handler := func(proc goprocess.Process) { ... }
p := goprocess.Go(func(proc goprocess.Process) {
  for {
    select {
    case <-fire:
      <-proc.Go(handler).Closed()
    case <-proc.Closing():
      return
    }
  }
})

go p.Close()
fire <- struct{}{} 
```
- order of `<-proc.Closing()` and `<-fire` is not determined
- so `proc.Go(handler)` (`proc.AddChild(q)`) races with `p.Close()` and may deadlock

I can fix this example with:

``` go
fire := make(chan struct{})
handler := func(proc goprocess.Process) { ... }
p := goprocess.Go(func(proc goprocess.Process) {
  for {
    select {
    case <-fire:

      // really make sure we're not closing.
      select {
      case <-proc.Closing():
        return
      default:
      }
      <-proc.Go(handler).Closed()

    case <-proc.Closing():
      return
    }
  }
})

go p.Close()
fire <- struct{}{} 
```

But I wonder whether the semantics of `AddChild` while `Closing()` should be: 
- it is always an error and may deadlock, or
- it is fine to add children while closing. these are immediately signaled to close.

**Comment by Stebalien** [comment]
Fixed per https://github.com/jbenet/goprocess/commit/2496b7cd1b4a4769db88cb3251a4bcb2d9d3383c.
